apiVersion: v1
kind: Secret
metadata:
  name: mlaas-helper-secret
type: Opaque
data:
  # Keycloak client secret for the confidential client
  KEYCLOAK_CLIENT_SECRET: "PASTE_YOUR_BASE64_ENCODED_CLIENT_SECRET_HERE" # e.g., echo -n 'very-secret-key' | base64 -> dmVyeS1zZWNyZXQta2V5
  # 3Scale Admin API key
  THREESCALE_ADMIN_API_KEY: "PASTE_YOUR_BASE64_ENCODED_3SCALE_API_KEY_HERE" # e.g., echo -n 'threescale-api-key' | base64 -> dGhyZWVzY2FsZS1hcGkta2V5