{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlaas-helper.configMapName" . }}
  labels:
    {{- include "mlaas-helper.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Application configuration
  app.conf: |
    # MLaaS Server Configuration
    # This file contains application-specific settings
    
    # Logging configuration
    LOG_LEVEL={{ .Values.configMap.data.LOG_LEVEL | default "INFO" }}
    LOG_FORMAT={{ .Values.configMap.data.LOG_FORMAT | default "%(asctime)s - %(levelname)s: %(message)s" }}
    
    # Flask configuration
    FLASK_ENV={{ .Values.env.FLASK_ENV }}
    FLASK_APP={{ .Values.env.FLASK_APP }}
    
    # Server configuration
    SERVER_HOST={{ .Values.configMap.data.SERVER_HOST | default "0.0.0.0" }}
    SERVER_PORT={{ .Values.configMap.data.SERVER_PORT | default "5000" }}
    
    # API configuration
    API_TIMEOUT={{ .Values.configMap.data.API_TIMEOUT | default "30" }}
    API_RETRY_COUNT={{ .Values.configMap.data.API_RETRY_COUNT | default "3" }}
  {{- if .Values.pip.enabled }}
  # Pip configuration for artifactory
  pip.conf: |
    [global]
    {{- if .Values.pip.trustedHost }}
    trusted-host = {{ .Values.pip.trustedHost }}
    {{- end }}
    {{- if .Values.pip.indexUrl }}
    index-url = {{ .Values.pip.indexUrl }}
    {{- end }}
    {{- if .Values.pip.extraIndexUrl }}
    extra-index-url = {{ .Values.pip.extraIndexUrl }}
    {{- end }}
    timeout = 60
    retries = 5
  {{- end }}
{{- end }} 