apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlaas-helper.fullname" . }}
  labels:
    {{- include "mlaas-helper.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlaas-helper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlaas-helper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlaas-helper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            # Application environment variables from values.yaml
            {{- range $key, $value := .Values.env }}
            {{- if $value }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            # Secret environment variables (only if secrets are provided)
            {{- if .Values.secrets.THREESCALE_ADMIN_API_KEY }}
            - name: THREESCALE_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlaas-helper.secretName" . }}
                  key: THREESCALE_ADMIN_API_KEY
            {{- end }}
            {{- if .Values.secrets.ARTIFACTORY_USERNAME }}
            - name: ARTIFACTORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlaas-helper.secretName" . }}
                  key: ARTIFACTORY_USERNAME
            {{- end }}
            {{- if .Values.secrets.ARTIFACTORY_PASSWORD }}
            - name: ARTIFACTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlaas-helper.secretName" . }}
                  key: ARTIFACTORY_PASSWORD
            {{- end }}
            {{- if .Values.secrets.ARTIFACTORY_URL }}
            - name: ARTIFACTORY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlaas-helper.secretName" . }}
                  key: ARTIFACTORY_URL
            {{- end }}
            # Additional environment variables for application configuration
            - name: API_TIMEOUT
              value: {{ .Values.configMap.data.API_TIMEOUT | default "30" | quote }}
            - name: API_RETRY_COUNT
              value: {{ .Values.configMap.data.API_RETRY_COUNT | default "3" | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.configMap.data.LOG_LEVEL | default "INFO" | quote }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.httpGet.path }}
              port: {{ .Values.startupProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.configMap.enabled }}
            - name: config
              mountPath: /app/config
              readOnly: true
            {{- end }}
            {{- if and .Values.pip.enabled .Values.secrets.ARTIFACTORY_USERNAME }}
            - name: pip-config
              mountPath: /home/appuser/.pip/pip.conf
              subPath: pip.conf
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.configMap.enabled }}
        - name: config
          configMap:
            name: {{ include "mlaas-helper.configMapName" . }}
        {{- end }}
        {{- if and .Values.pip.enabled .Values.secrets.ARTIFACTORY_USERNAME }}
        - name: pip-config
          configMap:
            name: {{ include "mlaas-helper.configMapName" . }}
            items:
              - key: pip.conf
                path: pip.conf
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 