{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlaas-helper.configMapName" . }}
  labels:
    {{- include "mlaas-helper.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- .Values.configMap.data | toYaml | nindent 2 }}
{{- end }} 